export const users = [
    {
      id: 1,
      name: "John Doe",
      age: 28,
      bioData: "Software Engineer with a passion for open-source projects.",
      city: "New York",
      country: "USA",
    },
    {
      id: 2,
      name: "Jane Smith",
      age: 34,
      bioData: "Digital marketer specializing in SEO and content strategy.",
      city: "London",
      country: "UK",
    },
    {
      id: 3,
      name: "Alice Johnson",
      age: 22,
      bioData: "Student pursuing a degree in Computer Science.",
      city: "Toronto",
      country: "Canada",
    },
    {
      id: 4,
      name: "Bob Brown",
      age: 45,
      bioData: "Entrepreneur with a focus on sustainable businesses.",
      city: "Sydney",
      country: "Australia",
    },
    {
      id: 5,
      name: "Charlie Davis",
      age: 30,
      bioData: "Graphic designer with a love for minimalist art.",
      city: "Berlin",
      country: "Germany",
    },
    {
      id: 6,
      name: "Diana Evans",
      age: 29,
      bioData: "Journalist covering international politics.",
      city: "Paris",
      country: "France",
    },
    {
      id: 7,
      name: "Ethan Harris",
      age: 35,
      bioData: "Chef specializing in fusion cuisine.",
      city: "Tokyo",
      country: "Japan",
    },
    {
      id: 8,
      name: "Fiona Clark",
      age: 27,
      bioData: "Yoga instructor and wellness coach.",
      city: "Mumbai",
      country: "India",
    },
    {
      id: 9,
      name: "George Lewis",
      age: 40,
      bioData: "Financial analyst with expertise in emerging markets.",
      city: "São Paulo",
      country: "Brazil",
    },
    {
      id: 10,
      name: "Hannah Walker",
      age: 26,
      bioData: "Environmental scientist researching climate change.",
      city: "Cape Town",
      country: "South Africa",
    },
    {
      id: 11,
      name: "Ian Hall",
      age: 33,
      bioData: "Musician and composer for film scores.",
      city: "Seoul",
      country: "South Korea",
    },
    {
      id: 12,
      name: "Julia Young",
      age: 31,
      bioData: "Author of bestselling fantasy novels.",
      city: "Moscow",
      country: "Russia",
    },
    {
      id: 13,
      name: "Kevin King",
      age: 38,
      bioData: "Architect specializing in sustainable design.",
      city: "Dubai",
      country: "UAE",
    },
    {
      id: 14,
      name: "Laura Scott",
      age: 24,
      bioData: "Social media influencer and travel blogger.",
      city: "Bangkok",
      country: "Thailand",
    },
    {
      id: 15,
      name: "Michael Green",
      age: 42,
      bioData: "Doctor specializing in cardiology.",
      city: "Rome",
      country: "Italy",
    },
    {
      id: 16,
      name: "Nina Adams",
      age: 29,
      bioData: "UX/UI designer with a focus on accessibility.",
      city: "Amsterdam",
      country: "Netherlands",
    },
    {
      id: 17,
      name: "Oscar White",
      age: 36,
      bioData: "Photographer capturing landscapes and wildlife.",
      city: "Vancouver",
      country: "Canada",
    },
    {
      id: 18,
      name: "Paula Martinez",
      age: 25,
      bioData: "Data scientist working on AI and machine learning.",
      city: "Madrid",
      country: "Spain",
    },
    {
      id: 19,
      name: "Quincy Taylor",
      age: 32,
      bioData: "Fitness trainer and nutritionist.",
      city: "Chicago",
      country: "USA",
    },
    {
      id: 20,
      name: "Rachel Lee",
      age: 28,
      bioData: "Event planner specializing in corporate events.",
      city: "Singapore",
      country: "Singapore",
    },
    {
      id: 21,
      name: "Samuel Wright",
      age: 39,
      bioData: "Lawyer with expertise in intellectual property.",
      city: "Hong Kong",
      country: "China",
    },
    {
      id: 22,
      name: "Tina Moore",
      age: 27,
      bioData: "Fashion designer with a focus on sustainable fashion.",
      city: "Stockholm",
      country: "Sweden",
    },
    {
      id: 23,
      name: "Uma Patel",
      age: 30,
      bioData: "Software developer specializing in blockchain technology.",
      city: "Bangalore",
      country: "India",
    },
    {
      id: 24,
      name: "Victor Rivera",
      age: 37,
      bioData: "Film director known for indie films.",
      city: "Los Angeles",
      country: "USA",
    },
    {
      id: 25,
      name: "Wendy Carter",
      age: 26,
      bioData: "Biologist researching marine ecosystems.",
      city: "Auckland",
      country: "New Zealand",
    },
    {
      id: 26,
      name: "Xander Brooks",
      age: 33,
      bioData: "Startup founder in the fintech industry.",
      city: "San Francisco",
      country: "USA",
    },
    {
      id: 27,
      name: "Yara Khan",
      age: 29,
      bioData: "Journalist covering technology and innovation.",
      city: "Islamabad",
      country: "Pakistan",
    },
    {
      id: 28,
      name: "Zack Morris",
      age: 31,
      bioData: "Product manager at a leading tech company.",
      city: "Austin",
      country: "USA",
    },
    {
      id: 29,
      name: "Anna Bell",
      age: 23,
      bioData: "Student studying environmental engineering.",
      city: "Oslo",
      country: "Norway",
    },
    {
      id: 30,
      name: "Ben Carter",
      age: 41,
      bioData: "Consultant in the healthcare industry.",
      city: "Zurich",
      country: "Switzerland",
    },
    {
      id: 31,
      name: "Cathy Wong",
      age: 28,
      bioData: "Digital artist and illustrator.",
      city: "Taipei",
      country: "Taiwan",
    },
    {
      id: 32,
      name: "David Kim",
      age: 34,
      bioData: "Entrepreneur in the e-commerce space.",
      city: "Seoul",
      country: "South Korea",
    },
    {
      id: 33,
      name: "Eva Lopez",
      age: 27,
      bioData: "Social worker advocating for mental health.",
      city: "Buenos Aires",
      country: "Argentina",
    },
  ];